import { Grid, CellState } from '../types';
const { GREEN, BLUE } = CellState;

export const SOLUTIONS: { puzzle: Grid }[] = [
  // Level 1
  { puzzle: [[GREEN, BLUE, BLUE, GREEN], [BLUE, BLUE, GREEN, GREEN], [GREEN, GREEN, BLUE, BLUE], [BLUE, GREEN, GREEN, BLUE]] },
  // Level 2
  { puzzle: [[BLUE, GREEN, BLUE, GREEN], [BLUE, GREEN, BLUE, GREEN], [GREEN, BLUE, GREEN, BLUE], [GREEN, BLUE, GREEN, BLUE]] },
  // Level 3
  { puzzle: [[GREEN, GREEN, BLUE, BLUE], [BLUE, BLUE, GREEN, GREEN], [GREEN, BLUE, GREEN, BLUE], [BLUE, GREEN, BLUE, GREEN]] },
  // Level 4
  { puzzle: [[BLUE, BLUE, GREEN, GREEN], [BLUE, GREEN, BLUE, GREEN], [GREEN, GREEN, BLUE, BLUE], [GREEN, BLUE, GREEN, BLUE]] },
  // Level 5
  { puzzle: [[BLUE, GREEN, GREEN, BLUE], [GREEN, BLUE, GREEN, BLUE], [BLUE, BLUE, GREEN, GREEN], [GREEN, GREEN, BLUE, BLUE]] },
  // Level 6
  { puzzle: [[GREEN, GREEN, BLUE, BLUE], [GREEN, BLUE, GREEN, BLUE], [BLUE, GREEN, BLUE, GREEN], [BLUE, BLUE, GREEN, GREEN]] },
  // Level 7
  { puzzle: [[BLUE, BLUE, GREEN, GREEN], [GREEN, GREEN, BLUE, BLUE], [GREEN, BLUE, GREEN, BLUE], [BLUE, GREEN, BLUE, GREEN]] },
  // Level 8
  { puzzle: [[BLUE, GREEN, GREEN, BLUE], [BLUE, GREEN, BLUE, GREEN], [GREEN, BLUE, BLUE, GREEN], [GREEN, BLUE, GREEN, BLUE]] },
  // Level 9
  { puzzle: [[GREEN, GREEN, BLUE, BLUE], [BLUE, BLUE, GREEN, GREEN], [GREEN, BLUE, GREEN, BLUE], [BLUE, GREEN, BLUE, GREEN]] },
  // Level 10
  { puzzle: [[BLUE, BLUE, GREEN, GREEN], [GREEN, GREEN, BLUE, BLUE], [BLUE, GREEN, BLUE, GREEN], [GREEN, BLUE, GREEN, BLUE]] },
  // Level 11
  { puzzle: [[BLUE, GREEN, GREEN, BLUE], [GREEN, GREEN, BLUE, BLUE], [GREEN, BLUE, BLUE, GREEN], [BLUE, BLUE, GREEN, GREEN]] },
  // Level 12
  { puzzle: [[GREEN, GREEN, BLUE, BLUE], [GREEN, BLUE, GREEN, BLUE], [BLUE, BLUE, GREEN, GREEN], [BLUE, GREEN, BLUE, GREEN]] },
  // Level 13
  { puzzle: [[GREEN, BLUE, GREEN, BLUE], [GREEN, BLUE, BLUE, GREEN], [BLUE, GREEN, GREEN, BLUE], [BLUE, GREEN, BLUE, GREEN]] },
  // Level 14
  { puzzle: [[BLUE, GREEN, BLUE, GREEN], [GREEN, GREEN, BLUE, BLUE], [BLUE, BLUE, GREEN, GREEN], [GREEN, BLUE, GREEN, BLUE]] },
  // Level 15
  { puzzle: [[GREEN, GREEN, BLUE, BLUE], [BLUE, BLUE, GREEN, GREEN], [GREEN, BLUE, GREEN, BLUE], [BLUE, GREEN, BLUE, GREEN]] },
  // Level 16
  { puzzle: [[GREEN, GREEN, BLUE, BLUE], [BLUE, BLUE, GREEN, GREEN], [BLUE, GREEN, GREEN, BLUE], [GREEN, BLUE, BLUE, GREEN]] },
  // Level 17
  { puzzle: [[BLUE, BLUE, GREEN, GREEN], [GREEN, GREEN, BLUE, BLUE], [BLUE, BLUE, GREEN, GREEN], [GREEN, GREEN, BLUE, BLUE]] },
  // Level 18
  { puzzle: [[BLUE, GREEN, GREEN, BLUE], [GREEN, GREEN, BLUE, BLUE], [BLUE, BLUE, GREEN, GREEN], [GREEN, BLUE, BLUE, GREEN]] },
  // Level 19
  { puzzle: [[GREEN, GREEN, BLUE, BLUE], [BLUE, BLUE, GREEN, GREEN], [BLUE, GREEN, GREEN, BLUE], [GREEN, BLUE, BLUE, GREEN]] },
  // Level 20
  { puzzle: [[BLUE, BLUE, GREEN, GREEN], [BLUE, GREEN, BLUE, GREEN], [GREEN, BLUE, GREEN, BLUE], [GREEN, GREEN, BLUE, BLUE]] },
];